language: node_js
sudo: false
node_js: 
  - '12'
cache: 
  directories:
    - node_modules
services: 
  - postgres
install: 
  - "npm install"
before_script:
  - npm install
  - psql -c "CREATE DATABASE nodelogin;" -U postgres
  - psql -c "CREATE USER nodelogin WITH PASSWORD '(ola)5902';" -U postgres
  - npm install -g sequelize-cli
  - sequelize db:migrate
  - npm install -g codecov
script:
  - npm run test
notifications:
  email: false