language: node_js
sudo: false
node_js: 
  - '12'
cache: 
  directories:
    - node_modules
services: 
  - postgresql
install: 
  - "npm install"
before_script:
  - npm install
  
  # - psql -c "CREATE DATABASE uiwbbdrf;" -U uiwbbdrf
  # - psql -c "CREATE USER uiwbbdrf WITH PASSWORD 'LPeb13nXxjgwp5i3xtMiiGL-IrFPEznO';" -U uiwbbdrf
  # - npm install -g sequelize-cli
  # - npm sequelize-cli db:migrate --url 'postgres://uiwbbdrf:LPeb13nXxjgwp5i3xtMiiGL-IrFPEznO@drona.db.elephantsql.com:5432/uiwbbdrf'
  # - npm install -g codecov
script:
  - npm run test
  - npm run coverage
  - npm run codecov
notifications:
  email: false