language: node_js
node_js:
    - "stable"
cache: npm
install:
    - npm ci
script:
    - npm run test
    - npm run report-coverage
env:
  global:
  - NODE_ENV=test
after_success:
  - bash <(curl -s https://codecov.io/bash)
